package com.harsha.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: employeeProto.proto
// Protobuf Java Version: 4.27.2

public final class EmployeeProto {
  private EmployeeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      EmployeeProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Add more fields as needed
     * </pre>
     *
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code Employee}
   */
  public static final class Employee extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Employee)
      EmployeeOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        Employee.class.getName());
    }
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      name_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmployeeProto.internal_static_Employee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmployeeProto.internal_static_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EmployeeProto.Employee.class, EmployeeProto.Employee.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_ = 0;
    /**
     * <pre>
     * Add more fields as needed
     * </pre>
     *
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EmployeeProto.Employee)) {
        return super.equals(obj);
      }
      EmployeeProto.Employee other = (EmployeeProto.Employee) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EmployeeProto.Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeProto.Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeProto.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeProto.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeProto.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static EmployeeProto.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static EmployeeProto.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static EmployeeProto.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmployeeProto.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Employee)
        EmployeeProto.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EmployeeProto.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EmployeeProto.internal_static_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EmployeeProto.Employee.class, EmployeeProto.Employee.Builder.class);
      }

      // Construct using EmployeeProto.Employee.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        age_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EmployeeProto.internal_static_Employee_descriptor;
      }

      @java.lang.Override
      public EmployeeProto.Employee getDefaultInstanceForType() {
        return EmployeeProto.Employee.getDefaultInstance();
      }

      @java.lang.Override
      public EmployeeProto.Employee build() {
        EmployeeProto.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EmployeeProto.Employee buildPartial() {
        EmployeeProto.Employee result = new EmployeeProto.Employee(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(EmployeeProto.Employee result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.age_ = age_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EmployeeProto.Employee) {
          return mergeFrom((EmployeeProto.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EmployeeProto.Employee other) {
        if (other == EmployeeProto.Employee.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                age_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       * Add more fields as needed
       * </pre>
       *
       * <code>int32 age = 3;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * Add more fields as needed
       * </pre>
       *
       * <code>int32 age = 3;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Add more fields as needed
       * </pre>
       *
       * <code>int32 age = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Employee)
    }

    // @@protoc_insertion_point(class_scope:Employee)
    private static final EmployeeProto.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmployeeProto.Employee();
    }

    public static EmployeeProto.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      @java.lang.Override
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EmployeeProto.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmployeeListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EmployeeList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    java.util.List<EmployeeProto.Employee> 
        getEmployeesList();
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    EmployeeProto.Employee getEmployees(int index);
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    int getEmployeesCount();
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    java.util.List<? extends EmployeeProto.EmployeeOrBuilder> 
        getEmployeesOrBuilderList();
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    EmployeeProto.EmployeeOrBuilder getEmployeesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code EmployeeList}
   */
  public static final class EmployeeList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:EmployeeList)
      EmployeeListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        EmployeeList.class.getName());
    }
    // Use EmployeeList.newBuilder() to construct.
    private EmployeeList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EmployeeList() {
      employees_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmployeeProto.internal_static_EmployeeList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmployeeProto.internal_static_EmployeeList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EmployeeProto.EmployeeList.class, EmployeeProto.EmployeeList.Builder.class);
    }

    public static final int EMPLOYEES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<EmployeeProto.Employee> employees_;
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    @java.lang.Override
    public java.util.List<EmployeeProto.Employee> getEmployeesList() {
      return employees_;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends EmployeeProto.EmployeeOrBuilder> 
        getEmployeesOrBuilderList() {
      return employees_;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    @java.lang.Override
    public int getEmployeesCount() {
      return employees_.size();
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    @java.lang.Override
    public EmployeeProto.Employee getEmployees(int index) {
      return employees_.get(index);
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    @java.lang.Override
    public EmployeeProto.EmployeeOrBuilder getEmployeesOrBuilder(
        int index) {
      return employees_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < employees_.size(); i++) {
        output.writeMessage(1, employees_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < employees_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, employees_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EmployeeProto.EmployeeList)) {
        return super.equals(obj);
      }
      EmployeeProto.EmployeeList other = (EmployeeProto.EmployeeList) obj;

      if (!getEmployeesList()
          .equals(other.getEmployeesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEmployeesCount() > 0) {
        hash = (37 * hash) + EMPLOYEES_FIELD_NUMBER;
        hash = (53 * hash) + getEmployeesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EmployeeProto.EmployeeList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeProto.EmployeeList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeProto.EmployeeList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeProto.EmployeeList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeProto.EmployeeList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmployeeProto.EmployeeList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmployeeProto.EmployeeList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static EmployeeProto.EmployeeList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static EmployeeProto.EmployeeList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static EmployeeProto.EmployeeList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmployeeProto.EmployeeList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static EmployeeProto.EmployeeList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmployeeProto.EmployeeList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EmployeeList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EmployeeList)
        EmployeeProto.EmployeeListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EmployeeProto.internal_static_EmployeeList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EmployeeProto.internal_static_EmployeeList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EmployeeProto.EmployeeList.class, EmployeeProto.EmployeeList.Builder.class);
      }

      // Construct using EmployeeProto.EmployeeList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (employeesBuilder_ == null) {
          employees_ = java.util.Collections.emptyList();
        } else {
          employees_ = null;
          employeesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EmployeeProto.internal_static_EmployeeList_descriptor;
      }

      @java.lang.Override
      public EmployeeProto.EmployeeList getDefaultInstanceForType() {
        return EmployeeProto.EmployeeList.getDefaultInstance();
      }

      @java.lang.Override
      public EmployeeProto.EmployeeList build() {
        EmployeeProto.EmployeeList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EmployeeProto.EmployeeList buildPartial() {
        EmployeeProto.EmployeeList result = new EmployeeProto.EmployeeList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(EmployeeProto.EmployeeList result) {
        if (employeesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            employees_ = java.util.Collections.unmodifiableList(employees_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.employees_ = employees_;
        } else {
          result.employees_ = employeesBuilder_.build();
        }
      }

      private void buildPartial0(EmployeeProto.EmployeeList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EmployeeProto.EmployeeList) {
          return mergeFrom((EmployeeProto.EmployeeList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EmployeeProto.EmployeeList other) {
        if (other == EmployeeProto.EmployeeList.getDefaultInstance()) return this;
        if (employeesBuilder_ == null) {
          if (!other.employees_.isEmpty()) {
            if (employees_.isEmpty()) {
              employees_ = other.employees_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEmployeesIsMutable();
              employees_.addAll(other.employees_);
            }
            onChanged();
          }
        } else {
          if (!other.employees_.isEmpty()) {
            if (employeesBuilder_.isEmpty()) {
              employeesBuilder_.dispose();
              employeesBuilder_ = null;
              employees_ = other.employees_;
              bitField0_ = (bitField0_ & ~0x00000001);
              employeesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEmployeesFieldBuilder() : null;
            } else {
              employeesBuilder_.addAllMessages(other.employees_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                EmployeeProto.Employee m =
                    input.readMessage(
                        EmployeeProto.Employee.parser(),
                        extensionRegistry);
                if (employeesBuilder_ == null) {
                  ensureEmployeesIsMutable();
                  employees_.add(m);
                } else {
                  employeesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<EmployeeProto.Employee> employees_ =
        java.util.Collections.emptyList();
      private void ensureEmployeesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          employees_ = new java.util.ArrayList<EmployeeProto.Employee>(employees_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          EmployeeProto.Employee, EmployeeProto.Employee.Builder, EmployeeProto.EmployeeOrBuilder> employeesBuilder_;

      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public java.util.List<EmployeeProto.Employee> getEmployeesList() {
        if (employeesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(employees_);
        } else {
          return employeesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public int getEmployeesCount() {
        if (employeesBuilder_ == null) {
          return employees_.size();
        } else {
          return employeesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public EmployeeProto.Employee getEmployees(int index) {
        if (employeesBuilder_ == null) {
          return employees_.get(index);
        } else {
          return employeesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder setEmployees(
          int index, EmployeeProto.Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.set(index, value);
          onChanged();
        } else {
          employeesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder setEmployees(
          int index, EmployeeProto.Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.set(index, builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder addEmployees(EmployeeProto.Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.add(value);
          onChanged();
        } else {
          employeesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder addEmployees(
          int index, EmployeeProto.Employee value) {
        if (employeesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmployeesIsMutable();
          employees_.add(index, value);
          onChanged();
        } else {
          employeesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder addEmployees(
          EmployeeProto.Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.add(builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder addEmployees(
          int index, EmployeeProto.Employee.Builder builderForValue) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.add(index, builderForValue.build());
          onChanged();
        } else {
          employeesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder addAllEmployees(
          java.lang.Iterable<? extends EmployeeProto.Employee> values) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, employees_);
          onChanged();
        } else {
          employeesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder clearEmployees() {
        if (employeesBuilder_ == null) {
          employees_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          employeesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public Builder removeEmployees(int index) {
        if (employeesBuilder_ == null) {
          ensureEmployeesIsMutable();
          employees_.remove(index);
          onChanged();
        } else {
          employeesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public EmployeeProto.Employee.Builder getEmployeesBuilder(
          int index) {
        return getEmployeesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public EmployeeProto.EmployeeOrBuilder getEmployeesOrBuilder(
          int index) {
        if (employeesBuilder_ == null) {
          return employees_.get(index);  } else {
          return employeesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public java.util.List<? extends EmployeeProto.EmployeeOrBuilder> 
           getEmployeesOrBuilderList() {
        if (employeesBuilder_ != null) {
          return employeesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(employees_);
        }
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public EmployeeProto.Employee.Builder addEmployeesBuilder() {
        return getEmployeesFieldBuilder().addBuilder(
            EmployeeProto.Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public EmployeeProto.Employee.Builder addEmployeesBuilder(
          int index) {
        return getEmployeesFieldBuilder().addBuilder(
            index, EmployeeProto.Employee.getDefaultInstance());
      }
      /**
       * <code>repeated .Employee employees = 1;</code>
       */
      public java.util.List<EmployeeProto.Employee.Builder> 
           getEmployeesBuilderList() {
        return getEmployeesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          EmployeeProto.Employee, EmployeeProto.Employee.Builder, EmployeeProto.EmployeeOrBuilder> 
          getEmployeesFieldBuilder() {
        if (employeesBuilder_ == null) {
          employeesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              EmployeeProto.Employee, EmployeeProto.Employee.Builder, EmployeeProto.EmployeeOrBuilder>(
                  employees_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          employees_ = null;
        }
        return employeesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:EmployeeList)
    }

    // @@protoc_insertion_point(class_scope:EmployeeList)
    private static final EmployeeProto.EmployeeList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmployeeProto.EmployeeList();
    }

    public static EmployeeProto.EmployeeList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmployeeList>
        PARSER = new com.google.protobuf.AbstractParser<EmployeeList>() {
      @java.lang.Override
      public EmployeeList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EmployeeList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmployeeList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EmployeeProto.EmployeeList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EmployeeList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023employeeProto.proto\"1\n\010Employee\022\n\n\002id\030" +
      "\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\",\n\014Empl" +
      "oyeeList\022\034\n\temployees\030\001 \003(\0132\t.Employeeb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Employee_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", });
    internal_static_EmployeeList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EmployeeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EmployeeList_descriptor,
        new java.lang.String[] { "Employees", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
